-- ==========================================
-- PHOENIXCYSEC.ID DATABASE SCHEMA
-- ==========================================

-- Admin Credentials (Application Side)
-- Use these to log in to /admin.html
-- Email:    admin@phoenix.id
-- Password: Phoenix_X_2026_Secure!  (UPDATED STRONG PASSWORD)

-- ==========================================

-- 1. Documentation Table
CREATE TABLE IF NOT EXISTS documentation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    title TEXT NOT NULL,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT,
    link TEXT
);

-- 2. Members Table
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    image_url TEXT NOT NULL,
    linkedin_url TEXT,
    instagram_url TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE documentation ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;

-- Create Policies: Allow Public Read Access
CREATE POLICY "Allow public read access docs" 
ON documentation FOR SELECT 
USING (true);

CREATE POLICY "Allow public read access members" 
ON members FOR SELECT 
USING (true);

-- Create Policies: Allow Anon Insert/Update/Delete (Use with caution!)
-- Since we are using a simple hardcoded admin panel without Supabase Auth for now,
-- we need to allow the anon key to modify data. 

CREATE POLICY "Allow anon modifications docs" 
ON documentation FOR ALL 
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow anon modifications members" 
ON members FOR ALL 
USING (true)
WITH CHECK (true);
