-- Create the documentation table
CREATE TABLE IF NOT EXISTS documentation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    title TEXT NOT NULL,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT,
    link TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE documentation ENABLE ROW LEVEL SECURITY;

-- Create Policy: Allow Public Read Access
CREATE POLICY "Allow public read access" 
ON documentation FOR SELECT 
USING (true);

-- Create Policy: Allow Anon Insert/Update/Delete (Use with caution!)
-- Since we are using a simple hardcoded admin panel without Supabase Auth for now,
-- we need to allow the anon key to modify data. 
-- IN PRODUCTION: You should set up Supabase Auth and restrict this to authenticated users.

CREATE POLICY "Allow anon modifications" 
ON documentation FOR ALL 
USING (true)
WITH CHECK (true);
