-- ==========================================
-- PHOENIXCYSEC.ID DATABASE SCHEMA
-- ==========================================

-- Admin Credentials (Application Side)
-- Use these to log in to /admin.html
-- Email:    admin@phoenix.id
-- Password: Phoenix_X_2026_Secure!

-- ==========================================

-- 1. Documentation Table
CREATE TABLE IF NOT EXISTS documentation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    title TEXT NOT NULL,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT,
    link TEXT
);

-- 2. Members Table
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    image_url TEXT NOT NULL,
    linkedin_url TEXT,
    instagram_url TEXT
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS)
-- ==========================================

ALTER TABLE documentation ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts (Idempotency Fix)
DROP POLICY IF EXISTS "Allow public read access docs" ON documentation;
DROP POLICY IF EXISTS "Allow anon modifications docs" ON documentation;
DROP POLICY IF EXISTS "Allow public read access members" ON members;
DROP POLICY IF EXISTS "Allow anon modifications members" ON members;

-- Create Policies
CREATE POLICY "Allow public read access docs" 
ON documentation FOR SELECT 
USING (true);

CREATE POLICY "Allow anon modifications docs" 
ON documentation FOR ALL 
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow public read access members" 
ON members FOR SELECT 
USING (true);

CREATE POLICY "Allow anon modifications members" 
ON members FOR ALL 
USING (true)
WITH CHECK (true);

-- ==========================================
-- STORAGE BUCKET CONFIGURATION
-- ==========================================

-- Create a bucket for images
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
-- 1. Allow Public Read Access
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING ( bucket_id = 'images' );

-- 2. Allow Anon Upload/Delete (For Admin Panel)
DROP POLICY IF EXISTS "Anon Upload" ON storage.objects;
CREATE POLICY "Anon Upload"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'images' );

DROP POLICY IF EXISTS "Anon Update" ON storage.objects;
CREATE POLICY "Anon Update"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'images' );

DROP POLICY IF EXISTS "Anon Delete" ON storage.objects;
CREATE POLICY "Anon Delete"
ON storage.objects FOR DELETE
USING ( bucket_id = 'images' );

-- ==========================================
-- SEED DATA (INITIAL MEMBERS)
-- ==========================================

-- Insert original members if they don't exist
-- Using DO block to check for existence before inserting to prevent duplicates on re-runs
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM members WHERE name = 'Ghifari Azhar') THEN
        INSERT INTO members (name, role, image_url, linkedin_url, instagram_url)
        VALUES ('Ghifari Azhar', 'Founder', '/ghifariazhar.jpg', 'https://www.linkedin.com/in/ghifari-azhar/', 'https://www.instagram.com/jonobaek/');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM members WHERE name = 'Riski Permana') THEN
        INSERT INTO members (name, role, image_url, linkedin_url, instagram_url)
        VALUES ('Riski Permana', 'Co Founder', '/riskipermana.jpg', 'https://www.linkedin.com/in/riskipermana/', 'https://instagram.com/rskprmn_668');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM members WHERE name = 'Farel Sapero') THEN
        INSERT INTO members (name, role, image_url, linkedin_url, instagram_url)
        VALUES ('Farel Sapero', 'Management', '/farelsapero.jpg', NULL, 'https://www.instagram.com/frellvero');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM members WHERE name = 'Musa H. Lubis') THEN
        INSERT INTO members (name, role, image_url, linkedin_url, instagram_url)
        VALUES ('Musa H. Lubis', 'Founder', '/musahamonangan.jpg', 'https://www.linkedin.com/in/musa-hamonangan-lubis-a719b9282/', 'https://www.instagram.com/ouashxy/');
    END IF;
END $$;
